runtime: python39

entrypoint: gunicorn -b :$PORT app:app

# Manual scaling settings
manual_scaling:
  instances: 2  # Set this to the number of instances you need

# Optional: Environment variables
env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "key.json"

# Handlers for static files and routing
handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
